# Default values for my-nextcloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1



image:
  repository: ghcr.io/pavelbaranov/nextcloud
  pullPolicy: Always
  tag: ""

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  name: my-nextcloud3-ingress
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: my-nextcloud3.k8s-1.sa
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 500Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

pvc:
  storage_class: nfs
  storage_size: 14Gi



# Additional volumes on the output Deployment definition.
volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: pv-claim-helm-nextcloud-app
####persistentVolumeClaim:
##### $  storageSize: 14Gi
volumeMounts:
  - name: persistent-storage
    mountPath: "/var/www/html/data"
nodeSelector: {}

tolerations: []

affinity: {}
