---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-helm-nextcloud3
  labels:
    {{- include "my-nextcloud.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.pvc.storage_class }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage_size }}