name: project-pipeline

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: ci-cd project
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          
      - name: "Hadolint"
        uses: jbergstroem/hadolint-gh-action@v1
        with:
          dockerfile: "./Docker/Dockerfile"

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GH_PAT }}


      #- name: Build and push
        #run: |
          #docker login --username pavelbaranov --password ${{ secrets.GH_PAT }} ghcr.io
          #docker build -t ghcr.io/pavelbaranov/nextcloud:${{ steps.tag_version.outputs.new_tag }} ./Docker
          #docker push ghcr.io/pavelbaranov/nextcloud:${{ steps.tag_version.outputs.new_tag }}

      - name: set up Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GH_PAT }}
          
      - name: helm-check
        uses: igabaydulin/helm-check-action@0.1.4
        env:
          CHART_LOCATION: ./my-nextcloud/
          CHART_VALUES: ./my-nextcloud/values.yaml   
      
      - name: Publish Helm charts
        run: |
          docker login --username pavelbaranov --password ${{ secrets.GH_PAT }} ghcr.io
          helm package my-nextcloud --version=${{ steps.tag_version.outputs.new_tag }} --app-version=${{ steps.tag_version.outputs.new_tag }}
          mv /home/runner/work/academy-project/academy-project/my-nextcloud-* ./helm-release
          ls
          ls helm-release/ 
          cd ..
          helm repo index --url https://pavelbaranov.github.io/academy-project/ --merge index.yaml .
          cat index.yaml
     
      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "Publish my-nextcloud:${{ steps.tag_version.outputs.new_tag }}"
          git push origin master